routes/web.php
<?php

use App\Post;
use App\Photo;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/photo', 'PhotoController@show');
Route::post('/view_photo', 'PhotoController@view')->name('view_photo.show');




Route::group(['middleware' => 'payel'], function () { 


});

Route::resource('admin/users', 'AdminuserController');


Route::get('/show', function () {
    $views = Post::all();
    return View('admin', compact('views'));
});

Route::resource('admin/posts', 'AdminpostController');


Route::get('/delete/{id}', function ($id) {
    $post = Post::findOrFail($id);
    $post->delete();
    return redirect('admin/posts');
});

Route::get('/view_photo/{id}', 'PhotoController@photo')->name('view.photo');

Route::post('/view/{id}', 'PhotoController@update_photo')->name('update.photo');

Route::get('/edit', function ($id) {
    $photos = Photo::findOrFail($id);
    return view('photo_show', compact('photos'));
});
Route::resource('/comment', 'PostCommentController');
Route::resource('/comment_reply', 'ReplyCommentController');

route::get('/blog_post', 'BlogPostController@blog_post')->name('blog_post.home');
route::get('/user_comment', 'PostCommentController@view_comment');

resources/views/admin.blade.php
<!DOCTYPE html>

<html lang="en">


<head>
@php
    $post = \App\Post::where('user_id',Auth::id())
                     ->first();

@endphp

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{{ url('vendors/iconfonts/mdi/css/materialdesignicons.min.css') }}">

  <link rel="stylesheet" href="{{ url('css/style.css') }}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{{ url('images/favicon.png') }}" />
</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="{{ route('blog_post.home') }}"><img src="{{url ('images/logo.svg') }}" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="{{ route('blog_post.home') }}"><img src="{{ url('images/logo-mini.svg') }}" alt="logo" /></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <div class="search-field d-none d-md-block">
          <form class="d-flex align-items-center h-100" action="#">
            <div class="input-group">
              <div class="input-group-prepend bg-transparent">
                <i class="input-group-text border-0 mdi mdi-magnify"></i>
              </div>
              <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
            </div>
          </form>
        </div>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown"
              aria-expanded="false">
              <div class="nav-profile-img">

                    @isset($post->photos->photo)
                     <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image"></>
                    @endisset

                    @empty($post->photos->photo)
                    <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="image" style="height:30px;border-radius:50%;margin-top:5px;">
                    @endempty

                  {{-- @foreach ($asif as $post) --}}
                {{-- @if(!is_null($post))
                <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image">
                @else
                <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="image">

                @endif --}}


                <span class="availability-status online"></span>
              </div>
              <div class="nav-profile-text">
               @if (Auth::check())
               {{ Auth::user()->name }} <span class="caret"></span>
           @endif


              </div>
            </a>
            <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a href="{{ url('photo') }}" class="dropdown-item">uplod photo</a>
                <a class="dropdown-item" href="{{ route('login') }}"> <i class="mdi mdi-cached mr-2 text-success"></i>{{ __('login') }}</a>

                <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="mdi mdi-logout mr-2 text-primary"></i> {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                      @csrf
                                  </form>


              </a>




              </li>
              </a>


    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
              <div class="nav-profile-image">

                    @isset($post->photos->photo)
                     <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image"
                    @endisset
                    @empty($post->photos->photo)
                    <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="image" style="height:30px;border-radius:50%;margin-top:5px;">
                    @endempty

                {{-- @if(!is_null($post))
                <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image">
                @else
                <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="image">

                @endif --}}

                <span class="login-status online"></span>
                <!--change to offline or busy as needed-->
              </div>
              <div class="nav-profile-text d-flex flex-column">
                <span class="font-weight-bold mb-2"> @if (Auth::check())
                  {{ Auth::user()->name }} <span class="caret"></span>
              @endif

              </div>
              <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
          </>

          <li class="nav-item">
            <a class="nav-link" href="{{ url('admin/users') }}">
              <span class="menu-title">Users</span>
              <i class="mdi mdi-home menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-title">category</span>
              <i class="menu-arrow"></i>
              <i class="mdi mdi-crosshairs-gps menu-icon"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{{url ('admin/users/create') }}">create</a></li>
                <li class="nav-item"> <a class="nav-link" href="{{ url('admin/posts') }}">Admin post</a></li>
                <li class="nav-item"> <a class="nav-link" href="{{ url('admin/posts/create') }}">Admin post create</a></li>
                <li class="nav-item"> <a class="nav-link" href="{{ url('admin/posts/edit') }}">Admin post edit</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ url('comment') }}">
              <span class="menu-title">Comment</span>
              <i class="mdi mdi-contacts menu-icon"></i>
            </a>
          </li>
          {{-- <li class="nav-item">
            <a class="nav-link" href="">
              <span class="menu-title">Forms</span>
              <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <span class="menu-title">Charts</span>
              <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <span class="menu-title">Tables</span>
              <i class="mdi mdi-table-large menu-icon"></i>
            </a>
          </li> --}}
        </ul>

      </nav>


      <!-- plugins:js -->
      <script src="{{ url('vendors/js/vendor.bundle.base.js') }}"></script>
      <script src="{{url ('vendors/js/vendor.bundle.addons.js') }}"></script>
      <script src="{{ url('js/off-canvas.js') }}"></script>
      <script src="{{url ('js/misc.js') }}"></script>
      <!-- endinject -->
      <!-- Custom js for this page-->
      <script src="{{url ('js/dashboard.js') }}"></script>
      @yield('content1')
      <!-- End custom js for this page-->
</body>

</html>

resources/views/blog_home.blade.php
@extends('layouts.app')
@section('content')
Home
@stop

resources/views/blog_post.blade.php
@extends('layouts.app')
@section('content')

{{-- @foreach ($posts as $post) --}}

@foreach ($posts as $post)
<div class="title">
        <h5>
                @if (Session::has('comment_message'))
                {{ session('comment_message') }}
                @endif
            </h5>
        <h1>{{ $post->title }}</h1>
        <p>By:{{ $post->user->name }}</p>

    </div>
<div class="container">

    <div class="row">
        <div class="col-sm-6">

    <div class="image">
            @isset($post->photos->photo)
            <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image"style="width:100%">
           @endisset

           @empty($post->photos->photo)
           <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="image" style="height:30px;border-radius:50%;margin-top:5px;">
           @endempty
        </div>
        </div>
        <div class="col-sm-6 body_part">
           <div class="body1">
                <p>{{ $post->body }}
                </p>



            </div>
        </div>

        <div class="link">
        {{ $posts->links() }}
    </div>
    </div>
    @endforeach



    <form action="{{ route('comment.store')}}" method="post">
        @csrf
            <div class="comments">
                <input type="hidden" name="post_id" value="{{ $post->id }}" >
    <div class="form-group">
        <textarea type="input" name="body" class="form-control" rows="5"></textarea>
      </div>
      <div class="form-group">
            <button type="submit" class="btn btn-success">Submit</button>
      </div>
    </div>
</form>

@php
    $comments = \App\Comment::whereIsActive(1)->get();

@endphp
{{-- @php
    $photo = \App\Photo::whereIsActive(1)->get();

@endphp --}}
    {{-- @if (count($comments)>0) --}}

    {{-- @foreach ($comments as $comment) --}}

    @foreach ($comments as $comment)
<div class="media border p-3">


        <img src="{{ asset('images/'.$post->photos->photo) }}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4>{{ $comment->author }}<small><i class="time">{{$comment->created_at->diffForHumans() }}</i></small></h4>
          <p>{{  $comment->body }}</p>






          {{-- comment reply --}}

          <form action="{{ route('comment_reply.store')}}" method="post">
            @csrf
                <div class="comments">
                    <input type="hidden" name="comment_id" value="{{ $comment->id }}" >
        <div class="form-group">
            <textarea type="input" name="body" class="form-control" rows="1"></textarea>
          </div>
          <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
    </form>

    @php
    $comment_reply = \App\CommentReply::all();

    @endphp


            @foreach($comment_reply as $commentans)


          <div class="media p-3">
            <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
            <div class="media-body">
              <h4>{{ $commentans->author }} <small><i>{{$commentans->created_at->diffForHumans() }}</i></small></h4>
              <p>{{  $commentans->body}}</p>
            </div>
          </div>
        </div>
    </div>

    @endforeach
    @endforeach






@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/photo_show.blade.php
@extends('admin')

@section('content1')

    <div class="container">

        <h1>Update Photo</h1>
        {{-- {{ Form::model(['method'=>'post','action'=>['PhotoController@update_photo']]) }}
   {{csrf_field()}}
    <div class="form-group">
        {!! Form::label('photo',$photos->photo) !!}
        {!! Form::file('photo',null,['class'=>'form-control'])!!}
    </div>
    <div class="form-group">
    {{ Form::submit('Edit',['class'=>'btn btn-danger']) }}
    </div>

        {{ Form::close() }} --}}

        <form action="{{ route('update.photo',$photos->id) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('POST') }}

                 <input type="file"name="photo" accept="image/*">
                <input type="submit" value="submit">
        </form>

</div>
@stop

resources/views/user_photo.blade.php
@extends('admin')

@section('content1')

    <div class="container">



    <div class="container">
        <h1>create</h1>
    {{ Form::open(array('route' =>'view_photo.show','method'=>'post','files'=>'true')) }}
   {{csrf_field()}}
    <div class="form-group">
        {!! Form::label('photo','Photo') !!}
        {!! Form::file('photo',null,['class'=>'form-control'])!!}
    </div>
    <div class="form-group">
    {{ Form::submit('save photo',['class'=>'btn btn-danger']) }}
    </div>

        {{ Form::close() }}

        {{-- <form action="{{ route('view_photo.show') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{-- <input type="text " name="title" placeholder="title"> --}}
                {{-- <input type="file" name="photo" accept="image/*">
                <input type="submit" value="submit">
        </form> --}}

</div>
@stop