routes/web.php
<?php

use App\Post;
use App\Photo;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/photo', 'PhotoController@show');
Route::post('/view_photo', 'PhotoController@view')->name('view_photo.show');




Route::group(['middleware' => 'payel'], function () { 


});

Route::resource('admin/users', 'AdminuserController');


Route::get('/show', function () {
    $views = Post::all();
    return View('admin', compact('views'));
});

Route::resource('admin/posts', 'AdminpostController');


Route::get('/delete/{id}', function ($id) {
    $post = Post::findOrFail($id);
    $post->delete();
    return redirect('admin/posts');
});

Route::get('/view_photo/{id}', 'PhotoController@photo')->name('view.photo');

Route::post('/view/{id}', 'PhotoController@update_photo')->name('update.photo');

Route::get('/edit', function ($id) {
    $photos = Photo::findOrFail($id);
    return view('photo_show', compact('photos'));
});
Route::resource('/comment', 'PostCommentController');
Route::resource('/comment_reply', 'ReplyCommentController');

route::get('/blog_post', 'BlogPostController@blog_post')->name('blog_post.home');
route::get('/user_comment', 'PostCommentController@view_comment');

app/Post.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'user_id',
        'category_id',
        'photo_id',
        'title',
        'body',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function photos()
    {
        return $this->belongsTo(Photo::class, 'photo_id');
    }
}

resources/views/admin/posts/create.blade.php
@extends('admin')

@section('content1')
<div class="container">
<h1>create</h1>
{{Form::open(array('action' => 'AdminpostController@store', 'method' => 'post'))}}
<div class="form-group">
        {!! Form::label('title','Title') !!}
        {!! Form::text('title',null,['class'=>'form-control'])!!}
</div>
<div class="form-group">
        {!! Form::label('category_id','Category') !!}
        {!! Form::select('category_id',array(''=>'option','0','1','2'),null,['class'=>'form-control'])!!}
</div>

<div class="form-group">
        {!! Form::label('body','Body') !!}
        {!! Form::textarea('body',null,['class'=>'form-control','rows'=>'3'])!!}
</div>
<div class="form-group">
        {!! Form::submit('create User',['class'=>'btn btn-primary'])!!}
</div>

{!! Form::close() !!}


@stop

resources/views/admin/posts/edit.blade.php
@extends('admin')

@section('content1')
<div class="container">

    <div class="row">
        <div class="col-sm-6"><h1>Edit Post</h1></div>
        <div class="col-sm-6">
                @isset($post->photos->photo)
                <li> <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image" style="height:30px;border-radius:50%;margin-top:5px;"></li>
                @endisset
                @empty($post->photos->photo)
                <img src="http://maestroselectronics.com/wp-content/uploads/bfi_thumb/blank-user-355ba8nijgtrgca9vdzuv4.jpg" alt="image" style="height:30px;border-radius:50%;margin-top:5px;">
                @endempty
            @php
    $photos = \App\Photo::where('photo_id',Auth::id())
                     ->first();

@endphp
            <a href="{{ url('/view_photo',$post->photos) }}"class="btn btn-primary">Edit</a>
        </div>
    </div>


{{ Form::model($post,['method'=>'patch','action'=>['AdminpostController@update',$post->id]]) }}
<div class="form-group">
        {!! Form::label('title','Title') !!}
        {!! Form::text('title',null,['class'=>'form-control'])!!}
</div>
<div class="form-group">
        {!! Form::label('category_id','Category') !!}
        {!! Form::select('category_id',array(''=>'option','0','1','2'),null,['class'=>'form-control'])!!}
</div>

<div class="form-group">
        {!! Form::label('body','Body') !!}
        {!! Form::textarea('body',null,['class'=>'form-control','rows'=>'3'])!!}
</div>
<div class="form-group">
        {!! Form::submit('Updated',['class'=>'btn btn-primary'])!!}
</div>

{!! Form::close() !!}


@stop

resources/views/admin/posts/index.blade.php
@extends('admin')

@section('content1')

<div class="container">

<div class="table">
<table>
<tr>
    <td>Id</td>
    <td>user</td>
    <td>categoey</td>
    <td>photo</td>
    <td>Title</td>
    <td>Body</td>
</tr>
@if($posts)
@foreach($posts as $post)
<tr>
    <th>{{ $post->id }}</th>
    @if($post->user)
     <th>{{ $post->user->name }}</th>
     @else
     <th></th>
     @endif
     @if($post)
    <th>{{ $post->category_id }}</th>
    @else
    <th></th>
    @endif
    @if($post->photos)
    <th>   <img src="{{ asset('images/'.$post->photos->photo) }}" alt="image"></th>
    @else
    <th></th>
    @endif
    @if($post)
    <th>{{ $post->title }}</th>
    @else
    <th></th>
    @endif
    @if($post)
    <th>{{ $post->body }}</th>
    @else
    <th></th>
    @endif
    <th>
        <a href="{{ route('posts.edit',$post->id) }}" class="btn btn-primary">Edit</a>
        {{-- {{ Form::model($post,['method'=>'delete','action'=>['AdminpostController@destroy',$post->id]]) }} --}}
        <a href="{{ url('/delete',$post->id) }}" class="btn btn-danger">Delete</button>  </a>
        {{-- {!! Form:: close() !!} --}}
    </th>

</tr>

@endforeach

@endif


</table>
{{ $posts->links() }}


</div>

</div>
@stop